// Problem 2 - Even Fibonacci Numbers
/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

#include <stdio.h>

typedef unsigned int ui32;

ui32 fib(ui32 num) {
	if(num < 2) return num;
	else return fib(num - 1) + fib(num - 2);
}

int main() {
	ui32 even_sum = 0;

	for(ui32 i = 1; fib(i) < 4000000; i++)
		if(!(fib(i) % 2)) even_sum += fib(i);

	printf("%d", even_sum);

	return 0;
}